# Generated by Django 4.2.25 on 2025-12-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_baseconhecimento_tarefa_etapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='arquivada',
            field=models.BooleanField(default=False, verbose_name='Arquivada?'),
        ),
    ]
