"""
Django settings for GerenciadorDeTarefas project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# We'll define SECRET_KEY, DEBUG and ALLOWED_HOSTS in environment-specific files.


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',
    'django_nyt',
    'mptt',
    'sorl.thumbnail',
    'home',
    'tasks',
    'users',
    'comentarios',
    # Wiki e seus Plugins
    'sekizai',
    'wiki',
    'wiki.plugins.attachments',
    'wiki.plugins.notifications',
    'wiki.plugins.images',
    'wiki.plugins.macros',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GerenciadorDeTarefas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sekizai.context_processors.sekizai',
            ],
        },
    },
]

WSGI_APPLICATION = 'GerenciadorDeTarefas.wsgi.application'


# DATABASES will be defined in environment-specific files.


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Define onde o Django deve procurar arquivos estáticos ANTES de procurar nas pastas 'static' dos apps.
STATICFILES_DIRS = [
    BASE_DIR / 'static', # Garante que a pasta 'static' na raiz do projeto seja incluída
    # Se estiver usando uma versão mais antiga do Django (< 3.1)
    # os.path.join(BASE_DIR, 'static'),
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/'

# STATIC_ROOT and MEDIA_ROOT will be defined in environment-specific files.


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ... outras configurações ...

# ----------------------------------------------------
# Configuração do Modelo de Usuário Customizado (Obrigatório)
# ----------------------------------------------------
AUTH_USER_MODEL = 'users.Usuarios'

# URLs de Autenticação
LOGIN_URL = 'login'              # Nome da rota de login
LOGIN_REDIRECT_URL = 'painel'    # Para onde vai após logar (Dashboard)
LOGOUT_REDIRECT_URL = 'home'     # Para onde vai após sair (Landing Page)

# EMAIL_BACKEND will be defined in environment-specific files.

# Configurações obrigatórias para o django-wiki
SITE_ID = 1

# Configuração de Mídia will be defined in environment-specific files.

# Permite que qualquer usuário logado crie artigos na raiz se ela não existir
WIKI_CAN_ADMIN = True

# Garante que apenas usuários logados vejam a wiki (opcional, mas recomendado para sistemas internos)
WIKI_ANONYMOUS_WRITE = False
WIKI_ANONYMOUS_VIEW = False


